[project]
name = "agent-system-plots"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ваше Имя", email = "ruslan.arkwen@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "openai>=3.14.1",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "streamlit>=1.64.0",
    "uvicorn>=0.53.0",
]

[project.scripts]
agent-system-plots = "agent_system_plots:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
